server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://10.43.173.180:3306/USER_INFO_DB_PERF?zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: next_user
    password: next_passwd
    driver-class-name: com.mysql.jdbc.Driver